### PR TITLE
fix: fix several bug

### PR DESCRIPTION
**Pull request by yqrashawn**
CU-4vv9nh
CU-4vv9yr
CU-4vva18
CU-4vv9zz

---

#

### CODE REVIEW

**Comment by angelia-yuqi-personal** [comment]
Task linked: [CU-4vv9zz 个人address页面显示mined blocks数据有问题](https://app.clickup.com/t/4vv9zz)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [CU-4vv9nh 个人address页面的交易列表只显示最近的，没有分页的历史记录查询功能](https://app.clickup.com/t/4vv9nh)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [CU-4vv9yr 个人address页面的token transfers里，地址link行为有问题](https://app.clickup.com/t/4vv9yr)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [CU-4vva18 个人address页面的filter在tab切换时有问题](https://app.clickup.com/t/4vva18)

**Review by angelia-yuqi-personal — APPROVED** [review]

**Review by zctocm — APPROVED** [review]

**Pull request merged**
