### PR TITLE
fix: SCAN-1228 SCAN-1226 stats jump with span SCAN-1225 typo and back…

### PR DESCRIPTION
**Pull request by jnoodle**
… btn feat SCAN-1223 SCAN-1224 home chart

**What kind of change does this PR introduce?**

**Did you add tests for your changes?**

**Does this PR introduce a breaking change?**

**What needs to be documented once your changes are merged?**

### CODE REVIEW

**Comment by angelia-yuqi-personal** [comment]
Task linked: [SCAN-1226 最佳统计-概览，时间间隔选24小时，点右上角查看十佳，跳转到对应tab页时间间隔变为了7天，应该和概览页保持一致](https://app.clickup.com/t/3719212/SCAN-1226)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [SCAN-1224 首页数据Dashboard图表，拖拽选择时间范围，时间被遮挡了，pc和移动端复现](https://app.clickup.com/t/3719212/SCAN-1224)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [SCAN-1225 Top Statistics-Overview中，中文环境下，右上角查看10佳，建议优化为“查看十佳”](https://app.clickup.com/t/3719212/SCAN-1225)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [SCAN-1223 首页数据 Dashboard,页面数据卡片出块间隔，吞吐率，日交易量，账户增长，点击未跳转进入对应图标详情页，同时需要补充一个点击效果](https://app.clickup.com/t/3719212/SCAN-1223)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [SCAN-1228 最佳统计-概览-代币，“代币交易账户总数”当前统计成了“发送交易总数”](https://app.clickup.com/t/3719212/SCAN-1228)

**Review by chain-txz — APPROVED** [review]

**Review by chain-txz — APPROVED** [review]

**Pull request merged**
